# -*- coding: utf-8 -*-
"""sem.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1beVUy_iNDtGlTC7zx3rQ_7PKwiMAyqSJ
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score, mean_squared_error,accuracy_score

df = pd.read_csv('/content/BostonHousing.csv')

print('Sample data:', df.head())
print('Summary of dataset:', df.describe())
print('Checking null values:', df.isnull().sum())

x = df[['rm', 'nox']]
y = df['tax']

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)
model = LinearRegression()
model

model.fit(x_train, y_train)

y_pred = model.predict(x_test)

print("R2 score of the model is:", r2_score(y_test, y_pred))
print("Mean Squared Error of the model is:", mean_squared_error(y_test, y_pred))